### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by Xobtah** [aCLr/rust-tdlib#4]
I am running the `main.rs` example program on Windows 10 (latest update).

I have built TDLib and placed the files in a lib/ folder in the project, I link it with a `build.rs` file that contains : 
```Rust
fn main() {
    println!("cargo:rustc-link-search=lib/tdlib/lib");
}
```
I have also placed TDLib's DLL into the target/debug/ folder.

At first I only had `rust-tdlib = "0.2.0"` in my Cargo.toml dependencies, didn't compile, but through trial and error I added libraries one by one, now this is my Cargo.toml file : 
```TOML
[package]
name = "myapp-rs"
version = "0.1.0"
authors = ["me"]
edition = "2018"
build = "build.rs"

[dependencies]
rust-tdlib = "0.2.0"
tokio = { version = "1.4.0", features = [ "macros", "rt", "time", "rt-multi-thread" ] }
log = "0.4"
env_logger = "0.8"
```

Now when I launch the `main.rs` example file I get these logs : 
```
C:/Users/me/.cargo/bin/cargo.exe run --color=always --package myapp-rs --bin myapp-rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\myapp-rs.exe`

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\myapp-rs.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

Process finished with exit code -1073741571 (0xC00000FD)
```

What am I doing wrong ?
